# -*- coding:utf-8 -*-

# Max turn.
MAX_TURN = 22

# DIALOGUE STATUS
DIALOGUE_STATUS_FAILED = 0
DIALOGUE_STATUS_SUCCESS = 1
DIALOGUE_STATUS_NOT_COME_YET = -1
DIALOGUE_STATUS_NOT_GET_ALL_SYMPTOMS = -2
DIALOGUE_STATUS_INFORM_WRONG_DISEASE = 2
DIALOGUE_STATUS_INFORM_RIGHT_SYMPTOM = 3
DIALOGUE_STATUS_REACH_MAX_TURN = -3
CONSTRAINT_CHECK_FAILURE = 4
# Special Actions.
CLOSE_DIALOGUE = "closing"
THANKS = "thanks"

# Slot value for unknown, placeholder and no value matches.
VALUE_UNKNOWN = "UNK"
VALUE_PLACEHOLDER = "placeholder"
VALUE_NO_MATCH = "No value matches."

# RESPONSE
I_DO_NOT_CARE = "I don't care."
I_DO_NOT_KNOW = "I don't know."
I_DENY = "No"

# Constraint Check
CONSTRAINT_CHECK_SUCCESS = 1


# Update condition
SUCCESS_RATE_THRESHOLD = 0.15
AVERAGE_WRONG_DISEASE = 7